exports.handler = async (event, context) => {
  const response = {
    statusCode: 200,
    headers: {
      "Access-Control-Allow-Origin": "https://rotadaamizade-adm.netlify.app"
    },
    body: JSON.stringify({ message: "Configuração cors" })
  };
  return response;
};